# Generated by Django 5.2.7 on 2025-10-10 07:42

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Must be a valid @betterask.erni email address', max_length=254, unique=True, validators=[authentication.validators.validate_erni_email]),
        ),
    ]
