[pytest]
DJANGO_SETTINGS_MODULE = puzzle_backend.config.settings_test
pythonpath = . puzzle_backend
testpaths = puzzle_backend
python_files = tests.py test_*.py *_tests.py
addopts =
    --nomigrations
    --reuse-db
    --cov=. --cov-report=term-missing
    --cov-fail-under=80
    --cov-config=.coveragerc
    --black
    --flake8
    -v
    --maxfail=1

filterwarnings =
    ignore::DeprecationWarning


[black]
line-length = 100
