# Generated by Django 5.2.7 on 2025-10-24 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_azure_id_user_updated_at_alter_user_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDepartmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to='users.department')),
            ],
            options={
                'verbose_name': 'Daily Department Score',
                'verbose_name_plural': 'Daily Department Scores',
                'ordering': ['-score'],
                'unique_together': {('department', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyIndividualScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Individual Score',
                'verbose_name_plural': 'Daily Individual Scores',
                'ordering': ['-score'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyDepartmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True)),
                ('month_start_date', models.DateField(db_index=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to='users.department')),
            ],
            options={
                'verbose_name': 'Monthly Department Score',
                'verbose_name_plural': 'Monthly Department Scores',
                'ordering': ['-score'],
                'unique_together': {('department', 'month_start_date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyIndividualScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True)),
                ('month_start_date', models.DateField(db_index=True, help_text='Date of the 1st of that month')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Individual Score',
                'verbose_name_plural': 'Monthly Individual Scores',
                'ordering': ['-score'],
                'unique_together': {('user', 'month_start_date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyDepartmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True)),
                ('week_start_date', models.DateField(db_index=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='users.department')),
            ],
            options={
                'verbose_name': 'Weekly Department Score',
                'verbose_name_plural': 'Weekly Department Scores',
                'ordering': ['-score'],
                'unique_together': {('department', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyIndividualScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True)),
                ('week_start_date', models.DateField(db_index=True, help_text='Date of the Sunday for that week')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Individual Score',
                'verbose_name_plural': 'Weekly Individual Scores',
                'ordering': ['-score'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
    ]
