# Generated by Django 4.2.25 on 2025-11-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDepartmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Daily Department Score',
                'verbose_name_plural': 'Daily Department Scores',
                'ordering': ['-score', 'department__name'],
            },
        ),
        migrations.CreateModel(
            name='DailyIndividualScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Daily Individual Score',
                'verbose_name_plural': 'Daily Individual Scores',
                'ordering': ['-score', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyDepartmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('month_start_date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Monthly Department Score',
                'verbose_name_plural': 'Monthly Department Scores',
                'ordering': ['-score', 'department__name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyIndividualScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('month_start_date', models.DateField(db_index=True, help_text='Date of the 1st of that month')),
            ],
            options={
                'verbose_name': 'Monthly Individual Score',
                'verbose_name_plural': 'Monthly Individual Scores',
                'ordering': ['-score', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyDepartmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('week_start_date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Weekly Department Score',
                'verbose_name_plural': 'Weekly Department Scores',
                'ordering': ['-score', 'department__name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyIndividualScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('week_start_date', models.DateField(db_index=True, help_text='Date of the Monday for that week')),
            ],
            options={
                'verbose_name': 'Weekly Individual Score',
                'verbose_name_plural': 'Weekly Individual Scores',
                'ordering': ['-score', 'user__username'],
            },
        ),
    ]
