# Generated by Django 4.2.25 on 2025-11-01 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('leaderboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyindividualscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklydepartmentscore',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='users.department'),
        ),
        migrations.AddField(
            model_name='monthlyindividualscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlydepartmentscore',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to='users.department'),
        ),
        migrations.AddField(
            model_name='dailyindividualscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailydepartmentscore',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to='users.department'),
        ),
        migrations.AddIndex(
            model_name='weeklyindividualscore',
            index=models.Index(fields=['week_start_date', '-score'], name='leaderboard_week_st_960f40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyindividualscore',
            unique_together={('user', 'week_start_date')},
        ),
        migrations.AddIndex(
            model_name='weeklydepartmentscore',
            index=models.Index(fields=['week_start_date', '-score'], name='leaderboard_week_st_164267_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklydepartmentscore',
            unique_together={('department', 'week_start_date')},
        ),
        migrations.AddIndex(
            model_name='monthlyindividualscore',
            index=models.Index(fields=['month_start_date', '-score'], name='leaderboard_month_s_47a881_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyindividualscore',
            unique_together={('user', 'month_start_date')},
        ),
        migrations.AddIndex(
            model_name='monthlydepartmentscore',
            index=models.Index(fields=['month_start_date', '-score'], name='leaderboard_month_s_705ac3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlydepartmentscore',
            unique_together={('department', 'month_start_date')},
        ),
        migrations.AddIndex(
            model_name='dailyindividualscore',
            index=models.Index(fields=['date', '-score'], name='leaderboard_date_a66e9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyindividualscore',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailydepartmentscore',
            index=models.Index(fields=['date', '-score'], name='leaderboard_date_f8f4c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailydepartmentscore',
            unique_together={('department', 'date')},
        ),
    ]
