# Generated by Django 5.2.7 on 2025-10-30 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboards', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydepartmentscore',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to='users.department'),
        ),
        migrations.AddField(
            model_name='dailyindividualscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlydepartmentscore',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to='users.department'),
        ),
        migrations.AddField(
            model_name='monthlyindividualscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklydepartmentscore',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='users.department'),
        ),
        migrations.AddField(
            model_name='weeklyindividualscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailydepartmentscore',
            unique_together={('department', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyindividualscore',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlydepartmentscore',
            unique_together={('department', 'month_start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyindividualscore',
            unique_together={('user', 'month_start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklydepartmentscore',
            unique_together={('department', 'week_start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyindividualscore',
            unique_together={('user', 'week_start_date')},
        ),
    ]
