from django.contrib import admin

from .models import (
    DailyDepartmentScore,
    DailyIndividualScore,
    MonthlyDepartmentScore,
    MonthlyIndividualScore,
    WeeklyDepartmentScore,
    WeeklyIndividualScore,
)

# Import custom admin site
from users.admin import admin_site


# ========== BASE PERMISSION MIXIN ==========
class LeaderboardReadOnlyMixin:
    """
    Leaderboards are read-only for everyone (generated automatically).
    Only Super Admins can view/modify them in admin.
    """
    
    def has_module_permission(self, request):
        """All admin roles can see Leaderboards section"""
        if not request.user.is_authenticated:
            return False
        return request.user.has_admin_access()
    
    def has_add_permission(self, request):
        """Nobody can add (auto-generated by system)"""
        return False
    
    def has_change_permission(self, request, obj=None):
        """Only Super Admins can edit (for manual corrections)"""
        if not request.user.is_authenticated:
            return False
        return request.user.is_superuser
    
    def has_delete_permission(self, request, obj=None):
        """Only Super Admins can delete"""
        if not request.user.is_authenticated:
            return False
        return request.user.is_superuser


# ========== INDIVIDUAL LEADERBOARD ADMINS ==========

@admin.register(DailyIndividualScore, site=admin_site)
class DailyIndividualScoreAdmin(LeaderboardReadOnlyMixin, admin.ModelAdmin):
    list_display = ('user', 'score', 'date')
    list_filter = ('date',)
    search_fields = ('user__username',)
    ordering = ('-date', '-score')
    date_hierarchy = 'date'
    readonly_fields = ('user', 'score', 'date')


@admin.register(WeeklyIndividualScore, site=admin_site)
class WeeklyIndividualScoreAdmin(LeaderboardReadOnlyMixin, admin.ModelAdmin):
    list_display = ('user', 'score', 'week_start_date')
    list_filter = ('week_start_date',)
    search_fields = ('user__username',)
    ordering = ('-week_start_date', '-score')
    date_hierarchy = 'week_start_date'
    readonly_fields = ('user', 'score', 'week_start_date')


@admin.register(MonthlyIndividualScore, site=admin_site)
class MonthlyIndividualScoreAdmin(LeaderboardReadOnlyMixin, admin.ModelAdmin):
    list_display = ('user', 'score', 'month_start_date')
    list_filter = ('month_start_date',)
    search_fields = ('user__username',)
    ordering = ('-month_start_date', '-score')
    date_hierarchy = 'month_start_date'
    readonly_fields = ('user', 'score', 'month_start_date')


# ========== DEPARTMENT LEADERBOARD ADMINS ==========

@admin.register(DailyDepartmentScore, site=admin_site)
class DailyDepartmentScoreAdmin(LeaderboardReadOnlyMixin, admin.ModelAdmin):
    list_display = ('department', 'score', 'date')
    list_filter = ('date',)
    search_fields = ('department__name',)
    ordering = ('-date', '-score')
    date_hierarchy = 'date'
    readonly_fields = ('department', 'score', 'date')


@admin.register(WeeklyDepartmentScore, site=admin_site)
class WeeklyDepartmentScoreAdmin(LeaderboardReadOnlyMixin, admin.ModelAdmin):
    list_display = ('department', 'score', 'week_start_date')
    list_filter = ('week_start_date',)
    search_fields = ('department__name',)
    ordering = ('-week_start_date', '-score')
    date_hierarchy = 'week_start_date'
    readonly_fields = ('department', 'score', 'week_start_date')


@admin.register(MonthlyDepartmentScore, site=admin_site)
class MonthlyDepartmentScoreAdmin(LeaderboardReadOnlyMixin, admin.ModelAdmin):
    list_display = ('department', 'score', 'month_start_date')
    list_filter = ('month_start_date',)
    search_fields = ('department__name',)
    ordering = ('-month_start_date', '-score')
    date_hierarchy = 'month_start_date'
    readonly_fields = ('department', 'score', 'month_start_date')