# Generated by Django 5.2.7 on 2025-10-20 06:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('game_type', models.CharField(choices=[('wordle', 'Wordle'), ('hangman', 'Hangman'), ('crossword', 'Crossword')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], max_length=10)),
                ('puzzle_data', models.JSONField(help_text='Encrypted puzzle content from AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'daily_puzzles',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'game_type'], name='daily_puzzl_date_c3a9e9_idx'), models.Index(fields=['is_active', 'date'], name='daily_puzzl_is_acti_1df72a_idx')],
                'unique_together': {('date', 'game_type', 'difficulty')},
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive days')),
                ('longest_streak', models.IntegerField(default=0, help_text='All-time longest streak')),
                ('last_completion_date', models.DateField(blank=True, null=True)),
                ('three_day_bonus_count', models.IntegerField(default=0)),
                ('seven_day_bonus_count', models.IntegerField(default=0)),
                ('thirty_day_bonus_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_streaks',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('period_start', models.DateField(help_text='Start date of period')),
                ('period_end', models.DateField(help_text='End date of period')),
                ('rank', models.IntegerField(db_index=True)),
                ('total_points', models.IntegerField(default=0)),
                ('puzzles_completed', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboards',
                'ordering': ['period', 'rank'],
                'indexes': [models.Index(fields=['period', 'rank'], name='leaderboard_period_cb452e_idx'), models.Index(fields=['period', 'period_start'], name='leaderboard_period_30e499_idx')],
                'unique_together': {('user', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserDailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('puzzles_completed', models.IntegerField(default=0, help_text='Count of puzzles completed today')),
                ('total_daily_score', models.IntegerField(default=0, help_text='Total points earned today')),
                ('daily_completion_bonus', models.IntegerField(default=0, help_text='Bonus for completing all puzzles')),
                ('is_complete', models.BooleanField(default=False, help_text='All 3 puzzles completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_daily_progress',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='user_daily__user_id_49df6e_idx'), models.Index(fields=['date', 'is_complete'], name='user_daily__date_f54061_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserPuzzleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='Time to complete in seconds', null=True)),
                ('base_score', models.IntegerField(default=0, help_text='100 for easy, 200 for hard')),
                ('hints_used', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='List of hint numbers used [1, 2, 3]', size=None)),
                ('hint_penalties', models.IntegerField(default=0, help_text='Total points deducted for hints')),
                ('bonus_points', models.IntegerField(default=0, help_text='Extra points from streaks, etc.')),
                ('final_score', models.IntegerField(default=0, help_text='Final calculated score')),
                ('attempts_data', models.JSONField(blank=True, default=dict, help_text='Game-specific attempt data')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_successful', models.BooleanField(default=False, help_text='True if puzzle solved, False if gave up')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.dailypuzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_puzzle_attempts',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='user_puzzle_user_id_e57b41_idx'), models.Index(fields=['puzzle', 'is_completed'], name='user_puzzle_puzzle__38d0f1_idx')],
                'unique_together': {('user', 'puzzle')},
            },
        ),
    ]
