# Generated by Django 4.2.7 on 2025-10-23 22:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('puzzle_completed', 'Puzzle Completed'), ('streak_milestone', 'Streak Milestone'), ('leaderboard_top', 'Leaderboard Top 3')], max_length=30)),
                ('puzzle_type', models.CharField(blank=True, max_length=20, null=True)),
                ('points', models.IntegerField(default=0)),
                ('tries', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'activity_feed',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCompletionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(db_index=True)),
                ('wordle_completed', models.BooleanField(default=False)),
                ('sudoku_completed', models.BooleanField(default=False)),
                ('ernigram_completed', models.BooleanField(default=False)),
                ('puzzles_completed_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_earned_today', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_completion_status',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('alltime', 'All-Time')], db_index=True, max_length=20)),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('score', models.IntegerField(default=0)),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leaderboard_cache',
                'ordering': ['period', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_type', models.CharField(choices=[('wordle', 'Wordle'), ('sudoku', 'Sudoku'), ('ernigram', 'ERNIgram')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], max_length=10)),
                ('puzzle_date', models.DateField(db_index=True)),
                ('solution_word', models.CharField(blank=True, max_length=10, null=True)),
                ('puzzle_string', models.TextField(blank=True, null=True)),
                ('solution_string', models.TextField(blank=True, null=True)),
                ('solution_phrase', models.CharField(blank=True, max_length=255, null=True)),
                ('clue', models.TextField(blank=True, null=True)),
                ('hints', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'puzzles',
                'ordering': ['-puzzle_date', 'puzzle_type'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_streak_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_completion_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'streaks',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_type', models.CharField(max_length=20)),
                ('tries', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('time_taken_ms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='games.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_type', models.CharField(max_length=20)),
                ('progress_data', models.JSONField(default=dict)),
                ('time_spent_ms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_saved', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_progress',
            },
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userdailyprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userdailyprogress',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userpuzzleattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpuzzleattempt',
            name='puzzle',
        ),
        migrations.RemoveField(
            model_name='userpuzzleattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstreak',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyPuzzle',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='UserDailyProgress',
        ),
        migrations.DeleteModel(
            name='UserPuzzleAttempt',
        ),
        migrations.DeleteModel(
            name='UserStreak',
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['puzzle_date', 'puzzle_type', 'difficulty'], name='puzzles_puzzle__5efc70_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['is_active', 'puzzle_date'], name='puzzles_is_acti_0d8003_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='puzzle',
            unique_together={('puzzle_type', 'difficulty', 'puzzle_date')},
        ),
        migrations.AddField(
            model_name='leaderboardcache',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailycompletionstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityfeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'puzzle_type'], name='user_progre_user_id_fbecae_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['last_saved'], name='user_progre_last_sa_cd799e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'puzzle')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'created_at'], name='submissions_user_id_92387d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['puzzle_type', 'created_at'], name='submissions_puzzle__aa7afb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-points_awarded'], name='submissions_points__478d66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'puzzle')},
        ),
        migrations.AddIndex(
            model_name='leaderboardcache',
            index=models.Index(fields=['period', 'rank'], name='leaderboard_period_a187aa_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardcache',
            index=models.Index(fields=['period', '-score'], name='leaderboard_period_cb3f28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardcache',
            unique_together={('period', 'user')},
        ),
        migrations.AddIndex(
            model_name='dailycompletionstatus',
            index=models.Index(fields=['user', 'completion_date'], name='daily_compl_user_id_386800_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycompletionstatus',
            index=models.Index(fields=['completion_date'], name='daily_compl_complet_6d323a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycompletionstatus',
            unique_together={('user', 'completion_date')},
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['-created_at'], name='activity_fe_created_9a1f22_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['event_type', '-created_at'], name='activity_fe_event_t_490cd8_idx'),
        ),
    ]
