# Generated by Django 4.2.25 on 2025-11-01 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErnigramPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_phrase', models.CharField(max_length=200)),
                ('clue', models.TextField()),
                ('date_to_be_used', models.DateField(db_index=True, unique=True)),
            ],
            options={
                'verbose_name': 'Ernigram Puzzle',
                'verbose_name_plural': 'Ernigram Puzzles',
                'ordering': ['-date_to_be_used'],
            },
        ),
        migrations.CreateModel(
            name='SudokuPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_string', models.TextField()),
                ('solution_string', models.TextField()),
                ('difficulty', models.CharField(max_length=20)),
                ('date_to_be_used', models.DateField(db_index=True, unique=True)),
            ],
            options={
                'verbose_name': 'Sudoku Puzzle',
                'verbose_name_plural': 'Sudoku Puzzles',
                'ordering': ['-date_to_be_used'],
            },
        ),
        migrations.CreateModel(
            name='WordlePuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_word', models.CharField(max_length=50)),
                ('date_to_be_used', models.DateField(db_index=True, unique=True)),
            ],
            options={
                'verbose_name': 'Wordle Puzzle',
                'verbose_name_plural': 'Wordle Puzzles',
                'ordering': ['-date_to_be_used'],
            },
        ),
        migrations.CreateModel(
            name='DailyPuzzle',
            fields=[
                ('date', models.DateField(db_index=True, primary_key=True, serialize=False)),
                ('ernigram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_puzzle', to='games.ernigrampuzzle')),
                ('sudoku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_puzzle', to='games.sudokupuzzle')),
                ('wordle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_puzzle', to='games.wordlepuzzle')),
            ],
            options={
                'verbose_name': 'Daily Puzzle',
                'verbose_name_plural': 'Daily Puzzles',
                'ordering': ['-date'],
            },
        ),
    ]
