# Generated by Django 4.2.25 on 2025-11-01 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DailyPuzzle',
            fields=[
                (
                    'date',
                    models.DateField(
                        default=django.utils.timezone.now,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeImageSource',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'employee_name',
                    models.CharField(
                        help_text='Full name of the employee (The solution phrase).',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    'clue_context',
                    models.CharField(
                        blank=True,
                        help_text='Role or project context for the AI clue.',
                        max_length=255,
                    ),
                ),
                (
                    'image_file',
                    models.ImageField(
                        help_text='Upload a picture of the employee.',
                        upload_to='ernigram_employees/',
                    ),
                ),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employee Image Source',
                'verbose_name_plural': 'Employee Image Sources',
            },
        ),
        migrations.CreateModel(
            name='ErnigramPuzzle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'solution_phrase',
                    models.CharField(
                        help_text='The phrase to guess (uppercase recommended)', max_length=255
                    ),
                ),
                ('clue', models.TextField()),
                ('date_to_be_used', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SudokuPuzzle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'solution_string',
                    models.CharField(
                        help_text='81 chars (1-9), the complete solution grid.', max_length=81
                    ),
                ),
                (
                    'puzzle_string_easy',
                    models.CharField(
                        help_text='81 chars (0-9), 0 for blank. Easy version (~50 givens).',
                        max_length=81,
                    ),
                ),
                (
                    'puzzle_string_hard',
                    models.CharField(
                        help_text='81 chars (0-9), 0 for blank. Hard version (~40 givens).',
                        max_length=81,
                    ),
                ),
                ('date_to_be_used', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordlePuzzle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'solution_word',
                    models.CharField(
                        help_text='The solution word (uppercase, 5 for easy, 6+ for hard)',
                        max_length=15,
                    ),
                ),
                (
                    'date_to_be_used',
                    models.DateField(
                        blank=True,
                        help_text='Optional: Date this specific puzzle instance should appear',
                        null=True,
                    ),
                ),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('EASY', 'Easy'), ('HARD', 'Hard')], default='EASY', max_length=4
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='wordlepuzzle',
            constraint=models.UniqueConstraint(
                fields=('date_to_be_used', 'difficulty'),
                name='unique_wordle_for_date_and_difficulty',
            ),
        ),
        migrations.AddField(
            model_name='ernigrampuzzle',
            name='employee_source',
            field=models.ForeignKey(
                blank=True,
                help_text='A link to the employee source if this is an employee puzzle.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='games.employeeimagesource',
            ),
        ),
        migrations.AddField(
            model_name='dailypuzzle',
            name='ernigram',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='daily_ernigrams',
                to='games.ernigrampuzzle',
            ),
        ),
        migrations.AddField(
            model_name='dailypuzzle',
            name='sudoku',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='daily_sudokus',
                to='games.sudokupuzzle',
            ),
        ),
        migrations.AddField(
            model_name='dailypuzzle',
            name='wordle_easy',
            field=models.ForeignKey(
                help_text='The 5-letter Wordle puzzle for the day (Easy difficulty)',
                limit_choices_to={'difficulty': 'EASY'},
                on_delete=django.db.models.deletion.PROTECT,
                related_name='daily_wordle_easy',
                to='games.wordlepuzzle',
            ),
        ),
        migrations.AddField(
            model_name='dailypuzzle',
            name='wordle_hard',
            field=models.ForeignKey(
                help_text='The 6+ letter Wordle puzzle for the day (Hard difficulty)',
                limit_choices_to={'difficulty': 'HARD'},
                on_delete=django.db.models.deletion.PROTECT,
                related_name='daily_wordle_hard',
                to='games.wordlepuzzle',
            ),
        ),
    ]
