# Generated by Django 4.2.25 on 2025-11-01 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypuzzle',
            name='wordle_easy',
            field=models.ForeignKey(help_text='The 5-letter Wordle puzzle for the day (Easy difficulty)', limit_choices_to={'difficulty': 'EASY'}, on_delete=django.db.models.deletion.PROTECT, related_name='daily_wordle_easy', to='games.wordlepuzzle'),
        ),
        migrations.AlterField(
            model_name='dailypuzzle',
            name='wordle_hard',
            field=models.ForeignKey(help_text='The 6+ letter Wordle puzzle for the day (Hard difficulty)', limit_choices_to={'difficulty': 'HARD'}, on_delete=django.db.models.deletion.PROTECT, related_name='daily_wordle_hard', to='games.wordlepuzzle'),
        ),
    ]
