# Generated by Django 5.2.7 on 2025-10-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlepuzzle',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('HARD', 'Hard')], default='EASY', max_length=4),
        ),
        migrations.AlterField(
            model_name='wordlepuzzle',
            name='date_to_be_used',
            field=models.DateField(blank=True, help_text='Optional: Date this specific puzzle instance should appear', null=True),
        ),
        migrations.AddConstraint(
            model_name='wordlepuzzle',
            constraint=models.UniqueConstraint(fields=('date_to_be_used', 'difficulty'), name='unique_wordle_for_date_and_difficulty'),
        ),
    ]
