# Generated by Django 5.2.7 on 2025-10-25 16:43

from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_wordlepuzzle_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ernigrampuzzle",
            name="date_to_be_used",
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sudokupuzzle",
            name="date_to_be_used",
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
    ]
