# Generated by Django 5.2.7 on 2025-10-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_ernigrampuzzle_date_to_be_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ernigrampuzzle',
            name='employee_image',
            field=models.ImageField(blank=True, help_text='Upload a picture of the employee. This will be blurred on the frontend.', null=True, upload_to='ernigram_employees/'),
        ),
    ]
