# Generated by Django 4.2.25 on 2025-11-01 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                (
                    'cost',
                    models.PositiveIntegerField(
                        help_text='The price of the reward in spendable points'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        help_text='Image for the reward (optional)',
                        null=True,
                        upload_to='rewards/',
                    ),
                ),
                (
                    'stock',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='How many are available? Null means infinite.',
                        null=True,
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Whether the reward is currently available in the shop',
                    ),
                ),
                (
                    'max_claims_per_user',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Max times a user can claim this. Null means infinite.',
                        null=True,
                    ),
                ),
            ],
            options={
                'ordering': ['cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClaimedReward',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'points_spent',
                    models.PositiveIntegerField(
                        help_text='How many points were spent at the time of claim'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('FULFILLED', 'Fulfilled'),
                            ('CLAIMED', 'Claimed'),
                        ],
                        default='CLAIMED',
                        max_length=20,
                    ),
                ),
                (
                    'reward',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='claims',
                        to='shop.reward',
                    ),
                ),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
    ]
