# Generated by Django 5.2.7 on 2025-10-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the reward (optional)', null=True, upload_to='rewards/'),
        ),
    ]
