# Generated by Django 5.2.7 on 2025-10-30 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimedreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='shop.reward'),
        ),
    ]
