# Generated by Django 5.2.7 on 2025-10-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_reward_imageurl_reward_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='max_claims_per_user',
            field=models.PositiveIntegerField(blank=True, help_text='Max times a user can claim this. Null means infinite.', null=True),
        ),
    ]
