# Generated by Django 5.2.7 on 2025-10-30 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
