# Generated by Django 5.2.7 on 2025-11-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='URL of the profile picture retrieved from Azure AD/Microsoft Graph.', max_length=500, null=True),
        ),
    ]
