# Generated by Django 5.2.8 on 2025-12-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_department_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='azure_id',
            field=models.CharField(
                help_text='Azure AD Object ID (immutable identifier)', max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('CONTENT_ADMIN', 'Content Admin'),
                    ('MODERATOR', 'Moderator'),
                    ('SHOP_MANAGER', 'Shop Manager'),
                    ('USER', 'Regular User'),
                ],
                default='USER',
                help_text='Assigns specific admin permissions to this user',
                max_length=20,
            ),
        ),
    ]
