# Generated by Django 5.2.8 on 2025-12-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_azure_id_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='azure_id',
            field=models.CharField(
                blank=True,
                help_text='Azure AD Object ID (immutable identifier)',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
