# Generated by Django 5.2.8 on 2025-12-15 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_azure_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='azure_id',
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text='Azure AD Object ID (immutable identifier)',
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
