# Generated by Django 5.2.7 on 2025-10-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_type', models.CharField(choices=[('wordle', 'Wordle'), ('sudoku', 'Sudoku'), ('ernigram', 'Ernigram')], max_length=20)),
                ('puzzle_id', models.PositiveIntegerField()),
                ('progress_data', models.JSONField(default=dict)),
                ('time_spent_ms', models.BigIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_type', models.CharField(choices=[('wordle', 'Wordle'), ('sudoku', 'Sudoku'), ('ernigram', 'Ernigram')], db_index=True, max_length=20)),
                ('puzzle_id', models.PositiveIntegerField()),
                ('puzzle_date', models.DateField(db_index=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], max_length=10)),
                ('points_awarded', models.IntegerField(db_index=True, default=0)),
                ('time_taken_ms', models.BigIntegerField()),
                ('tries', models.IntegerField()),
                ('final_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
