# Generated by Django 4.2.25 on 2025-11-01 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('COMPLETED', 'Completed'),
                            ('EXPIRED', 'Expired'),
                        ],
                        default='PENDING',
                        max_length=10,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleAttempt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'object_id',
                    models.PositiveIntegerField(
                        help_text='Primary key of the specific puzzle instance'
                    ),
                ),
                (
                    'progress_data',
                    models.JSONField(
                        help_text='Stores game state (e.g., Sudoku grid, Wordle guesses)'
                    ),
                ),
                ('time_spent_ms', models.BigIntegerField(default=0)),
                ('last_saved', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_saved'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'object_id',
                    models.PositiveIntegerField(
                        help_text='Primary key of the specific puzzle instance'
                    ),
                ),
                (
                    'puzzle_date',
                    models.DateField(
                        db_index=True,
                        help_text='The date of the puzzle being submitted (from DailyPuzzle.date)',
                    ),
                ),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('easy', 'Easy'), ('hard', 'Hard')],
                        default='easy',
                        help_text='Difficulty level played',
                        max_length=10,
                    ),
                ),
                ('points_awarded', models.IntegerField()),
                ('time_taken_ms', models.BigIntegerField(help_text='Time in milliseconds')),
                (
                    'tries',
                    models.PositiveIntegerField(
                        default=1, help_text='Number of guesses/attempts made'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        help_text='Points to the model of the puzzle (WordlePuzzle, SudokuPuzzle, etc.)',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
