# Generated by Django 4.2.25 on 2025-11-01 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puzzleattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['puzzle_date', 'puzzle_type'], name='gameplay_su_puzzle__d2f9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'puzzle_date'], name='gameplay_su_user_id_f060b8_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['points_awarded', 'puzzle_date'], name='gameplay_su_points__a6bf45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'puzzle_type', 'puzzle_date')},
        ),
        migrations.AddIndex(
            model_name='puzzleattempt',
            index=models.Index(fields=['user', 'puzzle_type', 'completed'], name='gameplay_pu_user_id_f49ef7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='puzzleattempt',
            unique_together={('user', 'puzzle_type', 'puzzle_id')},
        ),
    ]
