# Generated by Django 4.2.25 on 2025-11-01 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
        ('gameplay', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='submissions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='puzzleattempt',
            name='content_type',
            field=models.ForeignKey(
                help_text='Points to the model of the puzzle (WordlePuzzle, SudokuPuzzle, etc.)',
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AddField(
            model_name='puzzleattempt',
            name='daily_puzzle',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attempts',
                to='games.dailypuzzle',
            ),
        ),
        migrations.AddField(
            model_name='puzzleattempt',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='puzzle_attempts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='challenges_sent',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger_submission',
            field=models.OneToOneField(
                help_text='The submission the challenger wants the recipient to beat',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='challenge_as_challenger',
                to='gameplay.submission',
            ),
        ),
        migrations.AddField(
            model_name='challenge',
            name='recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='challenges_received',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='challenge',
            name='recipient_submission',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='challenge_as_recipient',
                to='gameplay.submission',
            ),
        ),
        migrations.AddField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='challenges_won',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(
                fields=['created_at', 'user'], name='gameplay_su_created_f464fd_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(
                fields=['created_at', 'user', 'points_awarded'],
                name='gameplay_su_created_0fd40a_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(
                fields=['content_type', 'object_id'], name='gameplay_su_content_cec32f_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(
                fields=['created_at', 'difficulty'], name='gameplay_su_created_8c9cf2_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='puzzleattempt',
            unique_together={('user', 'daily_puzzle', 'content_type', 'object_id')},
        ),
    ]
