# Generated by Django 5.2.7 on 2025-11-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_alter_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hints_used',
            field=models.IntegerField(
                default=0, help_text='Number of hints used during the attempt.'
            ),
        ),
    ]
