# Generated by Django 5.2.8 on 2025-12-15 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_submission_hints_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(
                fields=['status', 'recipient'], name='gameplay_ch_status_09bde4_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(
                fields=['status', 'challenger'], name='gameplay_ch_status_72097b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['expires_at'], name='gameplay_ch_expires_9a9103_idx'),
        ),
        migrations.AlterModelTable(
            name='challenge',
            table='gameplay_challenge',
        ),
    ]
