[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts =
    --nomigrations
    --reuse-db
    --cov=. --cov-report=term-missing
    --cov-fail-under=80
    --cov-config=.coveragerc
    --black
    --flake8
    -v

filterwarnings =
    ignore::DeprecationWarning


[flake8]
max-line-length = 100
exclude = migrations,venv,*.pyc,*.egg,build,dist


[black]
line-length = 100
