from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.utils import timezone

User = get_user_model()


# ============================================
# 1. PUZZLES TABLE
# ============================================
class Puzzle(models.Model):
    """
    Stores daily puzzles generated by Gemini AI.
    Two records per game type per day (Easy + Hard).
    """
    PUZZLE_TYPES = [
        ('wordle', 'Wordle'),
        ('sudoku', 'Sudoku'),
        ('ernigram', 'ERNIgram'),
    ]
    
    DIFFICULTY_CHOICES = [
        ('easy', 'Easy'),
        ('hard', 'Hard'),
    ]
    
    puzzle_type = models.CharField(max_length=20, choices=PUZZLE_TYPES)
    difficulty = models.CharField(max_length=10, choices=DIFFICULTY_CHOICES)
    puzzle_date = models.DateField(db_index=True)
    
    # Wordle-specific fields
    solution_word = models.CharField(max_length=10, blank=True, null=True)
    
    # Sudoku-specific fields
    puzzle_string = models.TextField(blank=True, null=True)
    solution_string = models.TextField(blank=True, null=True)
    
    # ERNIgram-specific fields
    solution_phrase = models.CharField(max_length=255, blank=True, null=True)
    clue = models.TextField(blank=True, null=True)
    
    # AI-generated hints (stored as JSON)
    hints = models.JSONField(default=dict, blank=True)
    # Example: {"hint_1": "...", "hint_2": "...", "hint_3": "..."}
    
    # Metadata
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'puzzles'
        unique_together = ['puzzle_type', 'difficulty', 'puzzle_date']
        indexes = [
            models.Index(fields=['puzzle_date', 'puzzle_type', 'difficulty']),
            models.Index(fields=['is_active', 'puzzle_date']),
        ]
        ordering = ['-puzzle_date', 'puzzle_type']
    
    def __str__(self):
        return f"{self.puzzle_type.title()} - {self.difficulty.title()} - {self.puzzle_date}"


# ============================================
# 2. USER PROGRESS TABLE (Auto-save)
# ============================================
class UserProgress(models.Model):
    """
    Stores in-progress game states (auto-saved every 2 seconds).
    Cleared when puzzle is submitted.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='progress')
    puzzle = models.ForeignKey(Puzzle, on_delete=models.CASCADE)
    puzzle_type = models.CharField(max_length=20)  # Denormalized for faster queries
    
    # Game state stored as JSON
    progress_data = models.JSONField(default=dict)
    # Example for Wordle: {"guesses": ["HOUSE"], "currentRow": 1, ...}
    
    # Timer tracking
    time_spent_ms = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    
    # Timestamps
    last_saved = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'user_progress'
        unique_together = ['user', 'puzzle']
        indexes = [
            models.Index(fields=['user', 'puzzle_type']),
            models.Index(fields=['last_saved']),
        ]
    
    def __str__(self):
        return f"{self.user.username} - {self.puzzle_type} - {self.puzzle.puzzle_date}"


# ============================================
# 3. SUBMISSIONS TABLE (Completed Puzzles)
# ============================================
class Submission(models.Model):
    """
    Final submissions when user completes a puzzle.
    One submission per user per puzzle.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='submissions')
    puzzle = models.ForeignKey(Puzzle, on_delete=models.CASCADE, related_name='submissions')
    puzzle_type = models.CharField(max_length=20)  # Denormalized
    
    # Performance metrics
    tries = models.IntegerField(validators=[MinValueValidator(1)])
    time_taken_ms = models.IntegerField(validators=[MinValueValidator(0)])
    points_awarded = models.IntegerField(default=0)
    
    # Timestamp
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    
    class Meta:
        db_table = 'submissions'
        unique_together = ['user', 'puzzle']
        indexes = [
            models.Index(fields=['user', 'created_at']),
            models.Index(fields=['puzzle_type', 'created_at']),
            models.Index(fields=['-points_awarded']),
        ]
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.user.username} - {self.puzzle_type} - {self.points_awarded}pts"


# ============================================
# 4. DAILY COMPLETION STATUS
# ============================================
class DailyCompletionStatus(models.Model):
    """
    Tracks how many puzzles user completed each day.
    Used for streak calculation.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='daily_status')
    completion_date = models.DateField(db_index=True)
    
    # Track individual puzzle completions
    wordle_completed = models.BooleanField(default=False)
    sudoku_completed = models.BooleanField(default=False)
    ernigram_completed = models.BooleanField(default=False)
    
    # Total count (0-3)
    puzzles_completed_count = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    
    # Points earned today
    points_earned_today = models.IntegerField(default=0)
    
    class Meta:
        db_table = 'daily_completion_status'
        unique_together = ['user', 'completion_date']
        indexes = [
            models.Index(fields=['user', 'completion_date']),
            models.Index(fields=['completion_date']),
        ]
        ordering = ['-completion_date']
    
    def __str__(self):
        return f"{self.user.username} - {self.completion_date} - {self.puzzles_completed_count}/3"
    
    def is_all_completed(self):
        """Check if user completed all 3 puzzles"""
        return self.puzzles_completed_count == 3


# ============================================
# 5. STREAKS TABLE
# ============================================
class Streak(models.Model):
    """
    Tracks user's consecutive days of completing ALL puzzles.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='streak')
    
    current_streak_count = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    max_streak_count = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    
    last_completion_date = models.DateField(null=True, blank=True)
    
    # Metadata
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'streaks'
    
    def __str__(self):
        return f"{self.user.username} - Current: {self.current_streak_count}, Max: {self.max_streak_count}"


# ============================================
# 6. LEADERBOARD CACHE
# ============================================
class LeaderboardCache(models.Model):
    """
    Pre-calculated leaderboard rankings for performance.
    Regenerated periodically.
    """
    PERIOD_CHOICES = [
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
        ('alltime', 'All-Time'),
    ]
    
    period = models.CharField(max_length=20, choices=PERIOD_CHOICES, db_index=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='leaderboard_entries')
    
    rank = models.IntegerField(validators=[MinValueValidator(1)])
    score = models.IntegerField(default=0)
    
    # For tracking rank changes
    previous_rank = models.IntegerField(null=True, blank=True)
    
    # Timestamp of calculation
    calculated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'leaderboard_cache'
        unique_together = ['period', 'user']
        indexes = [
            models.Index(fields=['period', 'rank']),
            models.Index(fields=['period', '-score']),
        ]
        ordering = ['period', 'rank']
    
    def __str__(self):
        return f"{self.period} - Rank {self.rank}: {self.user.username} ({self.score}pts)"


# ============================================
# 7. ACTIVITY FEED
# ============================================
class ActivityFeed(models.Model):
    """
    Recent puzzle completions by all users.
    Limited to last 50 events.
    """
    EVENT_TYPES = [
        ('puzzle_completed', 'Puzzle Completed'),
        ('streak_milestone', 'Streak Milestone'),
        ('leaderboard_top', 'Leaderboard Top 3'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='activities')
    event_type = models.CharField(max_length=30, choices=EVENT_TYPES)
    
    # Event details
    puzzle_type = models.CharField(max_length=20, blank=True, null=True)
    points = models.IntegerField(default=0)
    tries = models.IntegerField(null=True, blank=True)
    
    # Additional metadata (JSON for flexibility)
    metadata = models.JSONField(default=dict, blank=True)
    
    # Timestamp
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    
    class Meta:
        db_table = 'activity_feed'
        indexes = [
            models.Index(fields=['-created_at']),
            models.Index(fields=['event_type', '-created_at']),
        ]
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.user.username} - {self.event_type} - {self.created_at}"


# ============================================
# 8. UPDATED USER MODEL (Add to your existing User model)
# ============================================
"""
Add these fields to your existing User model in users/models.py:

class User(AbstractUser):
    # ... existing fields ...
    
    # NEW FIELDS FOR SPRINT 2:
    
    # Points tracking
    total_points_daily = models.IntegerField(default=0)
    total_points_weekly = models.IntegerField(default=0)
    total_points_monthly = models.IntegerField(default=0)
    total_points_alltime = models.IntegerField(default=0)  # Rename from total_points
    
    # Streak tracking (denormalized for quick access)
    current_streak_count = models.IntegerField(default=0)
    max_streak_count = models.IntegerField(default=0)
    
    # Activity tracking
    last_active = models.DateTimeField(default=timezone.now)
    
    # ... rest of existing fields ...
"""