"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Provide a default for safety
SECRET_KEY = os.environ.get("SECRET_KEY", "default-insecure-key-for-dev")
DEBUG = False
ENVIRONMENT = os.environ.get("ENVIRONMENT", "local")

if ENVIRONMENT == "production":
    DEBUG = False
    ALLOWED_HOSTS = ["better-play-erni.duckdns.org"]
else:
    DEBUG = True
    ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost").split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required by social-auth
    "social_django",
    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",  # Add this for Cross-Origin Resource Sharing
    # Your local apps
    'users.apps.UsersConfig',
    # 'games.apps.GamesConfig',
    'games.apps.GamesConfig',
    'gameplay.apps.GameplayConfig',  # <-- Ensure this line is present
    'leaderboards.apps.LeaderboardsConfig',
    'shop.apps.ShopConfig',
    'activity.apps.ActivityConfig',
]

CRON_CLASSES = [
    'games.cron.GenerateDailyPuzzlesCronJob',
    'leaderboards.cron.AggregateLeaderboardsCronJob',  # NEW
]

DJANGO_CRON_LOCK_BACKEND = 'django_cron.backends.lock.database.DatabaseLock'

SITE_ID = 1


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
        "TEST": {
            "NAME": os.environ.get("DB_TEST"),  # MUST match the name in the error message
            # "OPTIONS": {
            #     "init_session": "SELECT pg_terminate_backend(pg_stat_activity.pid) "
            #     "FROM pg_stat_activity "
            #     "WHERE pg_stat_activity.datname = current_database() "
            #     "AND pid <> pg_backend_pid();",
            # },
        },
        'OPTIONS': {'options': '-c search_path=public'},
        # ----------------------------------------------------
    }
}
CORS_ALLOW_CREDENTIALS = True  # Allow cookies to be sent cross-origin


# CORS Settings
if ENVIRONMENT == "production":
    CORS_ALLOWED_ORIGINS = ["https://better-play-erni.duckdns.org"]
    CSRF_TRUSTED_ORIGINS = ["https://better-play-erni.duckdns.org"]
else:
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
        if origin
    ]
    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
        if origin
    ]


AUTH_USER_MODEL = "users.User"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# --- Azure AD Credentials (Loaded from .env) ---
AZURE_AD_CLIENT_ID = os.environ.get("AZURE_AD_CLIENT_ID")
AZURE_AD_CLIENT_SECRET = os.environ.get("AZURE_AD_CLIENT_SECRET")
AZURE_AD_TENANT_ID = os.environ.get("AZURE_AD_TENANT_ID")
# This MUST match the 'Web' redirect URI in Azure App Registration AND users/urls.py path
AZURE_AD_REDIRECT_URI = os.environ.get(
    "AZURE_AD_REDIRECT_URI", "http://140.245.52.155/auth/callback/"
)


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


if ENVIRONMENT == "production":
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = None
    CSRF_COOKIE_SAMESITE = None
    CSRF_USE_SESSIONS = False  # ✅ store CSRF in session (safer for production)
    CSRF_COOKIE_HTTPONLY = False  # ✅ prevent JS access to CSRF cookie
    SESSION_COOKIE_HTTPONLY = True  # ✅ prevent JS access to session cookie
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    CSRF_USE_SESSIONS = False  # ✅ local dev convenience
    CSRF_COOKIE_HTTPONLY = False  # ✅ easier debugging
    SESSION_COOKIE_HTTPONLY = True  # still good practice even locally


SESSION_COOKIE_AGE = 86400  # Session lasts 1 day (optional)


# --- DRF Settings (Optional for basic session auth, but good to have) ---
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # Use SessionAuthentication for browser interaction
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        # Default to requiring authentication for API views
        "rest_framework.permissions.IsAuthenticated",
    ],
}

LOGIN_URL = "/auth/login/azuread-oauth2/"

if ENVIRONMENT == "production":
    FRONTEND_BASE_URL = os.getenv("DJANGO_BASE_URL", "https://better-play-erni.duckdns.org")
    LOGIN_REDIRECT_URL = f"{FRONTEND_BASE_URL}/auth/callback"
    LOGOUT_REDIRECT_URL = f"{FRONTEND_BASE_URL}/login"
else:
    FRONTEND_BASE_URL = os.getenv("DJANGO_BASE_URL", "http://localhost:5173")
    LOGIN_REDIRECT_URL = f"{FRONTEND_BASE_URL}/auth-callback"
    LOGOUT_REDIRECT_URL = f"{FRONTEND_BASE_URL}/login"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

USE_TZ = True
TIME_ZONE = "UTC"

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- MEDIA FILE CONFIGURATION ---
# This is the base URL from which media files will be served
# e.g., http://localhost:8000/media/rewards/my_image.png
MEDIA_URL = "/media/"

# This is the absolute path to the folder on your server where
# uploaded files will be stored.
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# ---


# 1. Directory where collectstatic will put all files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 2. Base URL for serving static files (e.g., in templates)
STATIC_URL = '/static/'


print(f"⚙️ Running in {ENVIRONMENT.upper()} mode | DEBUG={DEBUG}")


DATE_INPUT_FORMATS = [
    "%Y-%m-%d",  # '2025-11-06'
    "%m/%d/%Y",  # '11/06/2025'
    "%m/%d/%y",  # '11/06/25'
    "%b %d %Y",  # 'Nov 6 2025'
    "%b. %d, %Y",  # 'Nov. 6, 2025' <--- The format from your error
    "%d %b %Y",  # '6 Nov 2025'
    "%d %b, %Y",  # '6 Nov, 2025'
]
USE_L10N = True
