# Generated by Django 4.2.25 on 2025-11-01 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='activity_status', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_active', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'indexes': [models.Index(fields=['last_active'], name='activity_us_last_ac_f7f692_idx')],
            },
        ),
    ]
